DROP TABLE IF EXISTS Results;
DROP TABLE IF EXISTS Submissions;
DROP TABLE IF EXISTS Invites;
DROP TABLE IF EXISTS ClassMembers;
DROP TABLE IF EXISTS Assignments;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Accounts;
