name: Frontend QA
on: [push]
jobs:
  fmt:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./frontend
      run: yarn
    - name: ESLint
      working-directory: ./frontend
      run: yarn run eslint src --ext .ts,.tsx
    - name: Formatting
      working-directory: ./frontend
      run: yarn run prettier -c src
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./frontend
        run: yarn
      - name: Test
        working-directory: ./frontend
        run: yarn test
