name: Frontend QA
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: ESLint
      run: eslint frontend/src --ext .ts,.tsx
    - name: Formatting
      run: prettier -c frontend/src
